version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      dockerfile: php/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      MYSQL_HOST: database
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}

  database:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: key
      MYSQL_DATABASE: my-castle
      MYSQL_ROOT_PASSWORD: key
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
